### ISSUE TITLE
Google Calendar Applet - clicking on Configure doesn't respond

### ISSUE THREAD

**Issue by RickSlashee** [linuxmint/cinnamon-spices-desklets#318]
```
 * Cinnamon version (cinnamon 3.8.6)
 * Distribution - (Mint 19)
 * UUID: googleCalendar@javahelps.com
https://cinnamon-spices.linuxmint.com/desklets/view/35
 ```

**Issue**
It works, but on Linux Mint 19 clicking on Configure doesn't do anything.

**Comment by jaszhix** [comment]
Which desklet are you referring to? Please include the name/UUID in the title.

**Comment by RickSlashee** [comment]
Edited above.

**Comment by RickSlashee** [comment]
edited above.

**Comment by slgobinath** [comment]
The fix is on its way: https://github.com/linuxmint/cinnamon-spices-desklets/pull/319

**Comment by slgobinath** [comment]
Hi @RickSlashee,

The fix has been merged into the master branch. After updating the desklet, the config dialog must open. If it doesn't please do let me know.

**Comment by Leonidas967** [comment]
Hi slgobinath, everything is up to date. The configure button still won't work. Any fix for this?
